### ISSUE TITLE
[Wayland] Photoqt makes a lot of noise in journal logs on gnome

### ISSUE THREAD

**Issue by lotuspsychje** [luspi/photoqt#13]
Ubuntu 22.04 development branch/beta with kernel 5.15.0-25-generic (on Wayland/gnome)

Launching photoqt makes a lot of lines in the journal logs:

    apr 07 03:11:24 R00TB00K org.photoqt.PhotoQt.desktop[64710]: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway. 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/mainwindow.qml:257:5: QML PQThumbnailBar: Binding loop detected for property "y" 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/mainwindow.qml:331:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/mainwindow.qml:319:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/shortcuts/PQKeyShortcuts.qml:36:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/mainwindow/PQContextMenu.qml:319:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/mainwindow/PQContextMenu.qml:311:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/mainwindow/PQContextMenu.qml:305:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/mainwindow/PQThumbnailBar.qml:225:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/mainwindow/PQThumbnailBar.qml:211:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/mainwindow/PQLabels.qml:394:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/mainwindow/PQImage.qml:390:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/mainwindow/PQImage.qml:384:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/mainwindow/PQImage.qml:290:9: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/PQCmdReceived.qml:27:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/PQVariables.qml:70:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/PQVariables.qml:48:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/menumeta/PQMainMenu.qml:454:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/menumeta/PQMainMenu.qml:447:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/menumeta/PQMainMenu.qml:50:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/menumeta/PQMetaData.qml:364:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/elements/PQCheckbox.qml:69:13: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:25 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/menumeta/PQMetaData.qml:52:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:27 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/filedialog/PQFileDialog.qml:243:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:27 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/elements/PQComboBox.qml:98:9: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:27 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/elements/PQComboBox.qml:98:9: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:27 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/filedialog/parts/PQFileView.qml:642:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:27 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/filedialog/parts/PQFileView.qml:636:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:27 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/filedialog/parts/PQFileView.qml:65:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:27 R00TB00K org.photoqt.PhotoQt.desktop[64710]: qrc:/filedialog/parts/PQPlaces.qml:305:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } 
    apr 07 03:11:35 R00TB00K systemd[1153]: app-gnome-org.photoqt.PhotoQt-64710.scope: Consumed 3.948s CPU time. 

the program itself works properly after launch

**Comment by luspi** [comment]
Yes, this is caused by Qt 5.15 introducing a new syntax for specifying connections and deprecating the old syntax. Since PhotoQt is supported for Qt 5.9 onwards, I'm stuck with the old syntax causing Qt to throw all these warnings.

If you have Qt 15.1 installed, you can silence this warning (which is useless except maybe for developpers) for all Qt applications by setting the environment variable `QT_LOGGING_RULES` to `qt.qml.connections.warning=false`.

**Comment by luspi** [comment]
I just discovered a way to silence this warning from inside PhotoQt, just in time for the next release: 2cd162f5ab912fda4313e93cff866959b72d8d94
