### ISSUE TITLE
photoqt not launching or opening

### ISSUE THREAD

**Issue by aanishacharyaa** [luspi/photoqt#15]
this is what it says if launched from terminal

QQmlApplicationEngine failed to load component
qrc:/mainwindow.qml:242:5: Type PQTrayIcon unavailable
qrc:/PQTrayIcon.qml:24:1: module "Qt.labs.platform" is not installed

**Comment by luspi** [comment]
Hi @aanishacharyaa 

Thanks for reporting this. A few questions:

1) What platform are you using, Windows or Linux?
2) How did you install PhotoQt?
3) Which version of PhotoQt do you have?

**Comment by aanishacharyaa** [comment]
@luspi I'm using linux mint (Ubuntu 22) 64 bit and installed it using software manager (v2.5-4)

**Comment by luspi** [comment]
Okay, thanks! It seems like the package in the official repositories is missing the package `qml-module-qt-labs-platform` as dependency, installing that one should fix this.

You can also add the PhotoQt PPA in order to get the latest version from there (currently 2.9, soon 2.9.1).

**Comment by aanishacharyaa** [comment]
@luspi Thanks! Just to mention that even though your website has clear instructions for each platform, GitHub README is bit confusing at first glance. Maybe just put downloads link of your website in linux download section of the GitHub.

**Comment by alexmyczko** [comment]
Thanks for the solution, it'll be in the 3.0 package...
