### ISSUE TITLE
Potential crash when pressing any key on windows

### ISSUE THREAD

**Issue by LaaZa** [luspi/photoqt#16]
Version 2.9.1
Windows 11 22H2

PhotoQT is very likely to crash when pressing any key, even without any other input. Does not always happen but more often than not. I have not found a specific situation for it to happen or not to happen.

Does not happen on keys that by themselves(no modifier as the modifier key crashes) trigger a function.

**Comment by hadoooooouken** [comment]
Did you try latest version?
https://photoqt.org/downloads/windows/photoqt-2.9.1-2.exe

**Comment by LaaZa** [comment]
I'm not sure if that is different from the version I had, but still happens after installing that one. The crash will not happen if any key with a function is used first, but before that any key with no function(immediate, excludes modifiers) is pressed causes the crash.

**Comment by hadoooooouken** [comment]
Oh, I know this problem - already fixed. 
https://gitlab.com/lspies/photoqt/-/issues/160
I thought 2.9.1-2 has shipped with this fix.

While we are waiting for a new official release you can use my build (just unpack files to PQ's installed folder (but do a backup of original files just in case)):
[PhotoQt-fixed.zip](https://github.com/luspi/photoqt/files/10417306/PhotoQt-fixed.zip)
It has some UI changes and libraw (for RAW files generated by digital photo cameras) compiled with AVX cpu set (so your cpu should support it (any processor after 2011)).

**Comment by luspi** [comment]
Sorry for the delay in posting here, thanks for jumping in @hadoooooouken :)

Yes, this is fixed in the code, and will be part of v3.0. I hope to have that one ready later this week.

**Comment by luspi** [comment]
PhotoQt v3.0 is now released. You can find the latest installer on the website: https://photoqt.org/downpopupwindows
