### ISSUE TITLE
ESC key no longer able quit PhotoQT

### ISSUE THREAD

**Issue by DownshiftDX** [luspi/photoqt#17]
I have been using PhotoQT for a very long time as my primary viewer for images. I have always set an additional quit shortcut to ESC as this feels much more natural than using Q. A recent update made it so ESC is no longer able to quit the program which I have assigned in Settings > Shortcuts > Quit PhotoQT

**Comment by luspi** [comment]
Thanks for reporting. This had me stumped at first, as it seemed like PhotoQt at some point simply stopped checking what to do with the ESC key. I finally was able to track it down to a faulty check for the state of the contextmenu that caused the Escape key to be discarded in certain cases.

This is fixed now with 51c1e781afd7e9e09c6b361b90d95c8887641d1f and will ship with v3.2.

**Comment by DownshiftDX** [comment]
> Thanks for reporting. This had me stumped at first, as it seemed like PhotoQt at some point simply stopped checking what to do with the ESC key. I finally was able to track it down to a faulty check for the state of the contextmenu that caused the Escape key to be discarded in certain cases.
> 
> This is fixed now with [51c1e78](https://github.com/luspi/photoqt/commit/51c1e781afd7e9e09c6b361b90d95c8887641d1f) and will ship with v3.2.

Thank you for the prompt fix.
