### ISSUE TITLE
Swapped actions with Integrated Window Buttons for Navigation

### ISSUE THREAD

**Issue by Hrxn** [luspi/photoqt#21]
Hey, first time user of PhotoQt here, and let me start by saying that I'm really impressed with it so far!

Currently running PhotoQt v4.1 on Windows 10H22 (10.0.19045.3803)

Info from About > Configuration:
```
- Exiv2: 0.28.1
- pugixml: 1.13
- LibRaw: 0.21.1-Release
- QtPDF
- LibArchive: 3.6.2
- ImageMagick: 7.1.1
- FreeImage: 3.18
- DevIL: 180
- Video through Qt
- Qt image formats available:
    avif, avifs, bmp, cur, gif, heic, heif, icns, ico, jpeg, 
    jpg, jxl, pbm, pdf, pgm, png, ppm, svg, svgz, tga, 
    tif, tiff, wbmp, webp, xbm, xpm, 

```

I tried a code search first to see if it would turn up something relevant quick, and it seems I found the relevant part?

https://github.com/luspi/photoqt/blob/42627cedcffa007052ad4d417415aa27db659176/qml/ongoing/PQWindowButtons.qml#L95-L104

and

https://github.com/luspi/photoqt/blob/42627cedcffa007052ad4d417415aa27db659176/qml/ongoing/PQWindowButtons.qml#L117-L126

**Comment by luspi** [comment]
Thanks for letting me know (and thanks for the kind words), this is fixed with 6cd150063b8247f7d58583e9d586635933b1a2cc and will ship with 4.2.

**Comment by Hrxn** [comment]
Hey, thank you for the quick fix, really appreciate it!

There is something else I noticed, but I don't want to open an issue for this yet, until I know some more.
Maybe because this is something entirely specific to Windows? I don't know.

Anyway, maybe you can try to reproduce this on your end?

Here's what I did so far:

I've assigned some additional custom keyboard shortcuts, for example to *zoom to actual size* and *zoom to fit*, and those keyboard shortcuts work just as expected.
But the *Move view Up/Down/Left/Right* don't seem to work for me.
I've assigned them as new shortcuts, to both `Ctrl+UpArrow/DownArrow etc.` and the same with `Alt`, but there is nothing happening for me?

Panning/Moving an image with holding left mouse works, including "flicking" motion etc.

Or am I just completely misunderstanding the purpose of *Move view*?

**Comment by luspi** [comment]
No, you are understanding it correctly. And this is indeed not working at the moment. When I ported PhotoQt to Qt6 I at first was undecided what to do with the "Move to edge" actions (they were introduced as pre-4.0 there was no easy way to navigate to the edge of an image), and I totally forgot about the normal move actions as well. Let me fix that real quick.

**Comment by luspi** [comment]
Added with e6f74eed02be5900d7d573e33114c568bb26f570
