### ISSUE TITLE
[Feature Request] Add option to make PhotoQT Fully Transparent 

### ISSUE THREAD

**Issue by KAGEYAM4** [luspi/photoqt#23]
I am using Hyprland and would like to apply blur to PhotoQT, but because PhotoQT window is not fully tranparent, no blur is applied by Hyprland on PhotoQT window.

**Comment by luspi** [comment]
Thanks for the feature request. That was an easy thing to add, it has been added with 296b99378c52fc0402347ae77f9cec23cc27ca6a and will ship with v4.4 (likely to be released next week).

**Comment by KAGEYAM4** [comment]
Thank you so much.
