### ISSUE TITLE
What is the function of `SaveIcon` in Explorer Mode?

### ISSUE THREAD

**Issue by KAGEYAM4** [luspi/photoqt#25]
![image](https://github.com/luspi/photoqt/assets/75798544/869427e5-dcfc-4d6e-9d39-537fbcbf5d12)

There is no tooltip for this.

**Comment by luspi** [comment]
If active the file dialog remembers its location between sessions, instead of reverting back to the home folder each time. [I added a tooltip](https://github.com/luspi/photoqt/commit/a447d54de85437234bf8f2b96a28369978ceaaab) to it just now.
