### ISSUE TITLE
[Feature Request] Mosaic View in ExplorerWindow

### ISSUE THREAD

**Issue by KAGEYAM4** [luspi/photoqt#26]
Similar to these ->

https://stackoverflow.com/questions/17716325/show-images-from-gallery-in-mosaic-style-in-android
https://play-lh.googleusercontent.com/bAif910WrL_3vazxrsqMMzyaB1Q0ewvNdK0ktfN3lUibrA7cWg5j_IDlGRDaAKTT_Yo=w1052-h592

**Comment by luspi** [comment]
Thanks for the suggestion, I like this idea. I'm planning on releasing 4.4 later today and have a bunch of things I'm hoping to work on for 4.5 already, but if not for 4.5 I'll see what I can do for 4.6 with this.

**Comment by KAGEYAM4** [comment]
Thank you.


One thing i wanted to know, is github ok for issues or gitlab would be better as the repo is hosted there.

**Comment by luspi** [comment]
Though Gitlab would be preferred (to have all feature requests/bugs/etc. in the same place), both places are fine.

**Comment by luspi** [comment]
Closing as issue moved to GitLab: https://gitlab.com/lspies/photoqt/-/issues/254
