### ISSUE TITLE
Can't open the menu settings

### ISSUE THREAD

**Issue by LucasCodingM** [luspi/photoqt#29]
## Expected Behavior

I expect that in every case i can open the settings menu if this one is available

## Current Behavior

On some conditions the settings menu does not open

## Steps to Reproduce

1) Open the settings menu
2) Close the settings menu with the cross on the top right corner
3) Click on the settings menu again and the menu does not open

## Context (Environment)

- PhotoQt version: v4.5
- Operating system: Ubuntu 22.04
- Installed by: Source repository

## Comments
Here you can find debug log:
2024-05-18 13:08:45.756 [D] PQShortcuts.qml::executeInternalFunction::504: args: cmd = __settings
2024-05-18 13:08:45.756 [D] PQShortcuts.qml::executeInternalFunction::505: args: wheelDelta = undefined

**Comment by luspi** [comment]
Thanks for reporting this, fixed with 3a9999ed99770da1f989d0f01caf58423168996e.
