### ISSUE TITLE
Photoqt can't open some large PNGs

### ISSUE THREAD

**Issue by fccfc5d245c** [luspi/photoqt#31]
## Expected Behavior

Display the image when I open it in the usual ways

## Current Behavior

The loading animation appears very briefly and then nothing is displayed, but the program still works

## Steps to Reproduce

Launch the image from the file explorer or navigate to it from Phtoqt's ui

## Context (Environment)

- PhotoQt version: Flatpak 4.5
- Operating system: Debian 12.5
- Installed by: Discover

## Example Image
The file I was going to use as an example is 30Mb and I can't upload it here, but I'd be happy to send it in any other way, or paste the metadata or any other info the dev thinks is relevant. I could share a Wetransfer link to some images.

## Comments

- The images I'm talking about can be opened by every other software I've tried: Gwenview, Okular, Nomacs... 
- They're large PNGs, but some even heavier PNGs load without issues. I think it only happened with some screenshots from 2160p movies, taken with SMPlayer. But as I said, other screenshots (from the same movies and captured with the same settings) are displayed fine by Photoqt
- I haven't looked for what the problematic images have in common, but I could do it if I'm told what I should be looking for
- Otherwise, Photoqt works great, so I think this is a bug triggered by something in these particular PNGs

In any case, this isn't a big problem for me, but I'd be happy to help if you want to hunt this bug :)

**Comment by luspi** [comment]
Thanks for letting me know! If you could share a link to some sample images, that'd be fantastic!

**Comment by luspi** [comment]
One more question: After the image is "loaded" is nothing displayed or a black rectangle in place of the image? I discovered an issue when the image format (Indexed8 in the case I found) is not natively known to LCMS2 and a color profile is embedded. This resulted in a black rectangle being loaded instead of the image. I improved the handling of such cases with 1ae68664763d782cdc16b555255d4f26a5d063df.

**Comment by fccfc5d245c** [comment]
There isn't a black rectangle, the background remains translucent as if nothing has been loaded. I'll include a screenshot of the UI too and send you a link to Wetransfer, if that's alright with you. But it's going to have to be tomorrow, it's getting late here. Sorry for not noticing your response earlier!

**Comment by fccfc5d245c** [comment]
This Mega folder should work: https://mega.nz/folder/zmh3gQaZ#9-zdiVK8nz9A3U_e8C3Wlg

- All images here are readable by Gwenview, Okular and Nomacs, but not by Photoqt (except the UI screenshot)
- I noticed that their thumbnails also appear empty on Photoqt
- I'm changing my story a bit: All movies represented here gave me "blank" screenshots for every tested frame, except Tremors: the only Tremors' screenshot that can't be opened by Photoqt is this one, where I tweaked the Software Color Equalizer on SMPlayer before taking the snap, other screenshots from that same source were alright
- I'm including some images that have nothing to do with SMPlayer, but that's the black rectangle problem, I only found blanks on images generated by SMPlayer.

I hope this helps!

**Comment by luspi** [comment]
Fantastic, thanks! I fixed this issue with 82165069c7e35053b943ba4aea087daed2718712.

Those images are stored in the RGBA64 format with an embedded color profile. PhotoQt uses LittleCMS to apply such color profiles, and it appears that LittleCMS has an issue outputting an image in the RGBA64 format. I simply force it now to use a working image format instead.

**Comment by fccfc5d245c** [comment]
Great, keep up the good work!
