### ISSUE TITLE
When toggling from fullscreen to window mode the window bounces back to maximized size after shrinking to saved size and position

### ISSUE THREAD

**Issue by Anangaya** [luspi/photoqt#33]
## Expected Behavior

It should toggle between fullscreen and saved size and position

## Current Behavior

It's shrinking and then maximizing when I want it to just shrink. Which is forcing me to keep the window always maximized

## Context (Environment)

- PhotoQt version: v4.6
- Operating system: Windows 11
- Installed by: Website installer

## Example ~~Image~~Video

https://github.com/user-attachments/assets/b5cfc8d4-a35f-43ea-b116-f4348718823a

**Comment by luspi** [comment]
Thanks for the report! Curiously, on Linux I have the opposite problem (due to a limitation in Qt). Let me see what I can find out about this.

**Comment by luspi** [comment]
Sorry it took a little while, but this is now fixed with 4a0985ebba3342579fcc5c6b7b58d45e7eb0e6c9, PhotoQt now remembers the window state and restores the correct one.
