### ISSUE TITLE
Can't printscreen in fullscreen mode.

### ISSUE THREAD

**Issue by Mogekoff** [luspi/photoqt#5]
Can't printscreen in fullscreen mode.

**Comment by luspi** [comment]
Hi @Mogekoff 

My apologies for not replying earlier, I don't watch the GitHub repo as much as I probably should (the main repo is hosted over at GitLab)...

I just tested it and it works on my end. So to track down the issue, would you mind giving me the following info:
- What system are you using?
- What Desktop Environment are you using?
- What version of PhotoQt are you running?
