### ISSUE TITLE
request:  clicking empty area can does more useful things

### ISSUE THREAD

**Issue by aanishacharyaa** [luspi/photoqt#7]
Right now there's an option called 
"empty area around image" ticking it closes the viewer when clicking empty area around

Can a option be given that clicking left side empty area changes the image to previous one and 
clicking right side empty area changes the image to next one

I think this feature was available in Google Picasa. Thanks

**Comment by luspi** [comment]
Hi @aanishacharyaa 

Thanks for your suggestion. This is a great idea, I just added the necessary changes to support this: efe8fddd4e0ddf7b9350945e16b375b0c1a81230

The next release shipping this change should come very soon, probably some time later this month.
