### ISSUE TITLE
Loading multiple folders in slideshow mode causes weird behavior (on Windows)

### ISSUE THREAD

**Issue by christopherjc54** [luspi/photoqt#8]
Loading multiple folders and then starting a slideshow causes it to get stuck between the first 2 images.

I had selected 700+ pictures in 4 folders containing sub-folders with the images and then selected randomize and loop and then started the slideshow before the weird behavior started.

**Comment by luspi** [comment]
Hi @christopherjc54 

Thanks for letting me know! I was able to reproduce this bug and just added a fix to the code: f00fb7b4fcfdf508da76227ef97da6ebbd7dc384
The fix will ship with the next release of PhotoQt (probably later this month).

Thanks again!
