### ISSUE TITLE
Ugly filetype name in Windows

### ISSUE THREAD

**Issue by LaaZa** [luspi/photoqt#9]
Windows shows rather raw name for filetypes if photoqt is set to handle them.

For example where filetype should be shown as *PNG Image* or *Portable Network Graphics* (with older pqt) it is *pqt.pngfile* instead, similar happens for every filetype that photoqt is set to handle even though those filetypes are not photoqt specific.
This name is shown in many different places where a "friendly" name is supposed to be shown, like choosing filetype when saving or in explorer (including thirdparty replacements which use the same string)

![filetype_example](https://user-images.githubusercontent.com/6142286/153969356-d114c76b-3bc7-405a-83df-0613ca812b77.png)

![save_example](https://user-images.githubusercontent.com/6142286/153969632-d627a3cc-16f9-41ad-ac1d-e3ed42124ab9.png)

This issue appeared in **v2.4**, before that the names did change from default windows behaviour, but they did look more friendly. Tested different versions in windows sandbox to make sure it wasn't caused by anything else.

Tested in Windows 11 22000.493.

**Comment by luspi** [comment]
Hi @LaaZa

My apologies for the late reply. Due to some life events I had to put working on PhotoQt on hold for a few weeks...

Yes, in version 2.4, the filenames were indeed rather ugly on Windows. This should be fixed in the [latest version, v2.5](https://photoqt.org/downloads/windows/photoqt-2.5.exe).

**Comment by LaaZa** [comment]
No worries, you can take all the time you need and not like this is a big issue anyway. Keep up the good work.

Sorry if I left it unclear but I was talking about the latest version 2.5, what I meant was that this issue has been **since** 2.4.

And I reconfirmed just now that it does indeed happen with a clean install of 2.5.(windows sandbox)

**Comment by luspi** [comment]
Hm, I wonder if I accidentally used an older installer script file when setting up the installer... I'll look into it!

**Comment by LaaZa** [comment]
I don't think there has been a difference in the related files since 2.4 release, but I'm also not too knowlegeable about that installer stuff.

**Comment by luspi** [comment]
I just updated the Windows installer to the latest release, v2.6. I tested the installer on a fresh setup of Windows, and the filetype was shown with its "friendly" name. It should unregister and reregister the filetypes on install, so please give it a try and let me know if that worked.

**Comment by LaaZa** [comment]
Tested and working. Some of the names could be a bit more brief though: 
![image](https://user-images.githubusercontent.com/6142286/162577941-3da80a42-c5ac-4b4b-8496-5e909cc14f13.png)

By default windows shows *JPEG Image*, and perhaps that would be preferrable for common formats and maybe something more specific if it is rare or application specific format.

Thank you for your hard work. I'll report if I find anything else or have some ideas.
